FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build   
WORKDIR /CrudApi
   
# copy source
COPY crud.api/. .

RUN dotnet restore  
RUN dotnet build --configuration Release 
RUN dotnet publish -c Release -o out   

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime   
WORKDIR /CrudApi   
COPY --from=build /CrudApi/out ./

# Padrão de container ASP.NET
# ENTRYPOINT ["dotnet", "crud.api.dll"]
# Opção utilizada pelo Heroku
# CMD ASPNETCORE_URLS=http://*:$PORT dotnet crud.api.dll

ENTRYPOINT ["dotnet", "crud.api.dll"]